// Code generated by gocode.Generate; DO NOT EDIT.

package model

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/encoding/gocode/gocodec"
	_ "cuelang.org/go/pkg"
)

var cuegenvalProfile = cuegenMake("Profile", &Profile{})

// Validate validates x.
func (x *Profile) Validate() error {
	return cuegenCodec.Validate(cuegenvalProfile, x)
}

var cuegenCodec, cuegenInstance = func() (*gocodec.Codec, *cue.Instance) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0]
}()

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenInstance.Value().FieldByName(name, true)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 265 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xffD\x8e?K\xc4@\x10G\xe7\x97D0\xcbia/\xac\xdb(\x16\x89\x8d\b\x81\x13\x84C\xb0\x91C\xec\xc4boo\u0744K\xb2\xf1\xb2\xa9\xfc\x03\xeay\xfa%\xfc\xac+\t\xfe\xe9\x867\u031b\xb7\xe5?\x02\x04\xfe\x93\xe0_\x89N\xfcK\b\x8c\x8a\xbau\xb2Vz\"\x9d\xec9BDW\xd6:\x04\x84h*]\x8e\x11a\xe3\xbc(u\v\xbf&\xa2]\xff\x1e\x00\xdb7\xb7\xaa\xd3\xc9]Q\xfe\\\xae\t~Et\xe0\xdfB`\xf3\x9f\xaf\b\x01\xa2KY\xe9^\x14\r\x90\x11\x91\xff\xeaC\x00\xec\x9b\xc2\xe5\xdd,Q\xb6Jg\v\xedt\xd9\xea:5\xf7\xa5m\xda\xd4,e\x93\xa7\x95\x9d\xeb\x12\xc0\xce0\xa4\xbf\u0249\xea4\xae\x1b\xa9\x16\xd2h>\xec\x18\x9b.m\xff<\xe3\x0f,\xbe\x98d\x9c\xf3\xbd\xb1\xf8\xf3\n\x16\xf7)\x19\x1f?\v%\x9d\xe0\x8f\xfcP\u032d\x11,>3:\xe3\xfc\xf4\xf8\x88=1\xa2\xef\x00\x00\x00\xff\xff\x8f\xba?\x83,\x01\x00\x00")
